# Generated by Django 2.0.1 on 2018-01-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('dkim', 'dkim'), ('spf', 'spf')], default='dkim', max_length=8)),
                ('result', models.CharField(choices=[('fail', 'fail'), ('pass', 'pass'), ('softfail', 'softfail')], default='fail', max_length=4)),
                ('selector', models.CharField(max_length=20)),
                ('scope', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatedFeedbackPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(max_length=20)),
                ('dkim_pass', models.BooleanField()),
                ('spf_pass', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=254)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('count', models.PositiveIntegerField()),
                ('envelope_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmarc_reporting.Domain')),
                ('header_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmarc_reporting.Domain')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.FeedbackReport')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedFeedbackPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_dkim', models.CharField(choices=[('r', 'relaxed'), ('s', 'strict')], default='r', max_length=1)),
                ('alignment_spf', models.CharField(choices=[('r', 'relaxed'), ('s', 'strict')], default='r', max_length=1)),
                ('policy', models.CharField(choices=[('none', 'none'), ('quarantine', 'quarantine'), ('reject', 'reject')], default='none', max_length=10)),
                ('subdomain_policy', models.CharField(choices=[('none', 'none'), ('quarantine', 'quarantine'), ('reject', 'reject')], default='none', max_length=10)),
                ('percentage', models.IntegerField(default=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('extra_contact_info', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='policy_published',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.PublishedFeedbackPolicy'),
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.Reporter'),
        ),
        migrations.AddField(
            model_name='evaluatedfeedbackpolicy',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.FeedbackReportRecord'),
        ),
        migrations.AddField(
            model_name='authenticationresult',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.Domain'),
        ),
        migrations.AddField(
            model_name='authenticationresult',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmarc_reporting.FeedbackReportRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackreport',
            unique_together={('reporter', 'report_id')},
        ),
    ]
