# Generated by Django 3.0.2 on 2020-01-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmarc_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluatedfeedbackpolicy',
            options={'verbose_name_plural': 'Evaluated feedback policies'},
        ),
        migrations.AlterModelOptions(
            name='publishedfeedbackpolicy',
            options={'verbose_name_plural': 'Published feedback policies'},
        ),
        migrations.AlterField(
            model_name='authenticationresult',
            name='result',
            field=models.CharField(choices=[('fail', 'fail'), ('pass', 'pass'), ('softfail', 'softfail')], default='fail', max_length=8),
        ),
    ]
